```{r setup, include=FALSE}
install.packages("googleAnalyticsR", repos = "http://cran.us.r-project.org")
install.packages("googleAuthR", repos = "http://cran.us.r-project.org")
```

```{r setup, include=FALSE}
library("googleAuthR")
library("googleAnalyticsR")
library(lubridate)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(readr)
```

```{r read}

ga_auth(email = "bich.ngoc@ipricegroup.com")
```

```{r read}
account_list <- ga_account_list()

id_sg = '75448761'
id_id = '75897118'
id_hk = '75887160'
id_vn = '75895336'
id_my = '75229758'
id_ph = '75445974'
id_th = '79109064'
```


```{r setup}
#ids <- c(id_hk, id_id, id_my, id_ph, id_sg, id_vn, id_th)
#cc <- c('HK','ID','MY','PH','SG','VN','TH')
ids <- c(id_my, id_sg, id_vn, id_id, id_ph, id_th)
cc <- c('MY', 'SG', 'VN', 'ID', 'PH', 'TH')
```

```{r date range}
# date range = from today back to 8 days ago
dts = Sys.Date()

dts = dts - 3:195
#dts = dts -3 
```

print(dts) 


```{r metrics & dimension}
#get click data
click_metrics = c('ga:totalEvents', 'ga:uniqueEvents')
#dimensions = c('ga:eventCategory','ga:date','ga:deviceCategory',
#               'ga:eventAction','ga:eventLabel','ga:pagePath','ga:dimension10')
click_dimensions = c('ga:date','ga:operatingSystem', 'ga:eventLabel')


```

```{r filter & user segmentation}
#ga filters & segment
click_filter = "ga:eventCategory==conversion"

## make a segment element
my_segment = segment_ga4("name", segment_id = 'gaid::KEiJjDFZTse2AGRyhnHg_g')


```

```{r}
clicks = data.frame()
sessions = data.frame()
```

```{r}
#loop through countries and dates to download data day by day
#don't run this 24/7; we'll run out of api requests
for (i in 1:length(ids)){
  for (dt in 1:length(dts)){
    date_range = c(dts[dt], dts[dt])
    temp = data.frame()
    temp <- google_analytics(ids[i], date_range,
                               metrics = click_metrics,
                               dimensions = click_dimensions,
                               filters = click_filter,
                               # segments = my_segment,
                               max = -1, anti_sample = TRUE)
    temp$CC = cc[i]
    temp$Date = dts[dt]
    #temp$Site = ids[i]
    if (!is.null(dim(temp))) {
      clicks = rbind(clicks,temp)
    }
  }
}

clicks$month=month(clicks$Date)
```

```{r to csv}
# to csv for checking, can skip this one
write_csv(clicks, 'C:\\Users\\Rachel Le\\iPrice Group\\Crazy Rich Asians - Documents\\T42\\Team files\\Rach\\GA API\\GA_clicks_by_OS_gross_unique.csv')
```


```{r metrics & dimension}
# get sessions
session_metrics = c('ga:sessions')
#dimensions = c('ga:eventCategory','ga:date','ga:deviceCategory',
#               'ga:eventAction','ga:eventLabel','ga:pagePath','ga:dimension10')
session_dimensions = c('ga:date', 'ga:deviceCategory')

## make a segment element
my_segment = segment_ga4("name", segment_id = 'gaid::KEiJjDFZTse2AGRyhnHg_g')

```

```{r metrics & dimension}
#loop through countries and dates to download data day by day
#don't run this 24/7; we'll run out of api requests
for (i in 1:length(ids)){
  for (dt in 1:length(dts)){
    date_range = c(dts[dt], dts[dt])
    temp = data.frame()
    temp <- google_analytics(ids[i], date_range,
                               metrics = session_metrics,
                               dimensions = session_dimensions,
                               # filters = session_filter,
                               segments = my_segment,
                               max = -1, anti_sample = TRUE)
    temp$CC = cc[i]
    temp$Date = dts[dt]
    #temp$Site = ids[i]
    if (!is.null(dim(temp))) {
      sessions = rbind(sessions,temp)
    }
  }
}

sessions$month=month(sessions$Date)
```

```{r to csv}
# to csv for checking, can skip this one
write_csv(sessions, 'C:\\Users\\Rachel Le\\iPrice Group\\Crazy Rich Asians - Documents\\T42\\Team files\\Rach\\GA API\\GA_multi-merchant-sessions.csv')
```